sudo: required
services:
  - docker

before_install:
  - docker build -t bengurney1/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run bengurney bengurney1/docker-react npm test -- --coverage

after_success:
  - docker build -t bengurney1/multi-client ./client
  - docker build -t bengurney1/multi-nginx ./nginx
  - docker build -t bengurney1/multi-server ./server
  - docker build -t bengurney1/multi-worker ./worker

# login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub
  - docker push bengurney/multi-client
  - docker push bengurney/multi-nginx
  - docker push bengurney/multi-server
  - docker push bengurney/multi-worker
